[package]
name = "wcr"
version = "0.1.0"
edition = "2024"
authors = ["Phil Brass <pbrass@gmail.com>"]

[dependencies]
anyhow = "*"
clap = { version = "4", features = ["derive"] }
unicode-segmentation = "1"
predicates = "*"
assert_cmd="*"
rand = "0"
pretty_assertions = "*"
